<h1 id="pageTitle">Please leave a comment</h1>

<?php echo $this->form ?>

<h2>Comments</h2>

<?php if (!empty ($this->comments)): ?>
<?php foreach ($this->comments as $comment): ?>

<div class="commentItem">
    <div class="commentFullName"><?php echo $this->escape($comment->getFullName())?></div>
    <div class="commentContent"><cite><?php echo $this->escape($comment->getComment())?></cite></div>
</div>
<?php endforeach;?>
<?php else: ?>
<p>No comments provided yet</p>
<?php endif; ?>